name: Static Site Sanity Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ main ]

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files
      run: ls -R
